apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-backend
  template:
    metadata:
      labels:
        app: social-backend
    spec:
      containers:
        - name: socialbackend
          image: sankalp1011/socialbackend:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: social-backend-service
spec:
  selector:
    app: social-backend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
