apiVersion: v1
kind: Service
metadata:
  name: social-backend-service
spec:
  selector:
    app: social-backend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
